# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dZzLJNc7uv38O7PnMzwlzz6jJ-txUslS
"""

# Clone the repository.
!git clone https://github.com/ultralytics/YOLOv5

# Commented out IPython magic to ensure Python compatibility.
# Install dependencies.
# %cd YOLOv5
!pip install -r requirements.txt
!pip install onnx

# Download .pt model.
!wget https://github.com/ultralytics/YOLOv5/releases/download/v6.1/YOLOv5l.pt

# Export to ONNX.
!python export.py --weights models/YOLOv5l.pt --include onnx